
server:
  port: 8030

spring:
  application:
    name: pay-service
  datasource:
    url: jdbc:mysql://192.168.0.104:3307/pay?useSSL=false
    username: ruhr_new
    password: RUHR@007mysql
    driver-class-name: com.mysql.cj.jdbc.Driver